export { default as EyeIcon } from './EyeIcon'
export { default as DeleteIcon } from './DeleteIcon'
export { default as SearchIcon } from './SearchIcon'
// export { default as UploadIcon } from './UploadIcon'
// export { default as GoogleIcon } from './GoogleIcon'
// export { default as FacebookIcon } from './FacebookIcon'
// export { default as TwitterIcon } from './TwitterIcon'
// export { default as GithubIcon } from './GithubIcon'
